
# Saudi Master Data Generator — Self-contained Notebook

This notebook implements the uploaded Saudi master-data generation specification. It creates these DataFrames:

- `territory_df`
- `salesperson_df`
- `van_df`
- `customer_df`
- `holiday_df`
- `config_df`
- `rfm_scores_df`

It also validates foreign keys and business rules, then writes CSV outputs plus `data_quality_report.json`.

In [14]:
# !pip install pandas folium

In [15]:
# !python -m pip install ortools

In [16]:

# Self-contained Saudi master/reference data generator
# Run this notebook top-to-bottom. It writes outputs into ./saudi_master_data_output

import sys
import subprocess
import importlib.util
from pathlib import Path
from datetime import date, datetime, timedelta
import json
import math
import random
import string


def ensure_package(package_name, import_name=None):
    """Install package if missing. Safe for local/Jupyter execution."""
    import_name = import_name or package_name
    if importlib.util.find_spec(import_name) is None:
        subprocess.check_call([sys.executable, "-m", "pip", "install", package_name])

ensure_package("pandas")
ensure_package("numpy")
ensure_package("faker")

import numpy as np
import pandas as pd
from faker import Faker

try:
    fake = Faker(["ar_SA", "en_US"])
except Exception:
    fake = Faker("en_US")

# -----------------------------
# Static specification inputs
# -----------------------------

TERRITORIES = [
    {
        "territory_id": "TER_RUH",
        "territory_name": "Riyadh Central",
        "center_lat": 24.7136,
        "center_lng": 46.6753,
        "radius_km": 25,
        "warehouse_lat": 24.5790,
        "warehouse_lng": 46.8237,
        "warehouse_address": "Industrial Area, Riyadh",
    },
    {
        "territory_id": "TER_JED",
        "territory_name": "Jeddah North",
        "center_lat": 21.5433,
        "center_lng": 39.1728,
        "radius_km": 22,
        "warehouse_lat": 21.3429,
        "warehouse_lng": 39.2357,
        "warehouse_address": "Al Khomrah Logistics Area, Jeddah",
    },
    {
        "territory_id": "TER_DMM",
        "territory_name": "Dammam Metro",
        "center_lat": 26.4207,
        "center_lng": 50.0888,
        "radius_km": 20,
        "warehouse_lat": 26.2926,
        "warehouse_lng": 50.1629,
        "warehouse_address": "2nd Industrial City, Dammam",
    },
]

LOCALITIES = {
    "TER_RUH": [
        ("Olaya", 24.7115, 46.6746),
        ("Al Malaz", 24.6676, 46.7351),
        ("Al Sulaymaniyah", 24.7012, 46.7112),
        ("Al Yasmin", 24.8271, 46.6302),
        ("Hittin", 24.7636, 46.6022),
    ],
    "TER_JED": [
        ("Al Rawdah", 21.5656, 39.1652),
        ("Al Hamra", 21.5262, 39.1611),
        ("Al Safa", 21.5854, 39.2181),
        ("Al Salamah", 21.5948, 39.1485),
        ("Al Zahra", 21.6152, 39.1335),
    ],
    "TER_DMM": [
        ("Al Faisaliyah", 26.4282, 50.0786),
        ("Al Shati", 26.4701, 50.1124),
        ("Al Mazruiyah", 26.4481, 50.0962),
        ("Al Badiyah", 26.4021, 50.0587),
        ("Al Nuzha", 26.4337, 50.0433),
    ],
}

CITY_CODES = {"TER_RUH": "RUH", "TER_JED": "JED", "TER_DMM": "DMM"}
PLATE_PREFIXES = {"TER_RUH": "RU", "TER_JED": "JE", "TER_DMM": "DM"}

SAUDI_SALESPERSON_NAMES = [
    "Abdullah Al-Qahtani", "Fahad Al-Otaibi", "Mohammed Al-Harbi",
    "Nasser Al-Dossari", "Khalid Al-Ghamdi", "Saeed Al-Zahrani",
    "Yousef Al-Mutairi", "Majed Al-Shammari", "Ahmed Al-Anazi",
    "Salem Al-Rashidi", "Omar Al-Shehri", "Hassan Al-Yami",
    "Rashid Al-Malki", "Ibrahim Al-Subaie", "Mansour Al-Qahtani",
    "Waleed Al-Harbi", "Bilal Khan", "Imran Ahmed", "Sameer Khan",
    "Nadeem Ali", "Arif Rahman", "Mustafa Hussain",
]

OWNER_NAMES = [
    "Al Rajhi", "Al Othman", "Al Harbi", "Al Qahtani", "Al Ghamdi",
    "Al Zahrani", "Al Dossari", "Al Mutairi", "Al Shammari", "Al Anazi",
    "Al Rashid", "Al Saleh", "Al Malki", "Al Subaie", "Al Shehri",
]

BUSINESS_PREFIXES = [
    "Al Noor", "Al Waha", "Al Baraka", "Al Safa", "Al Madina",
    "Al Qassim", "Al Riyadh", "Al Jazeera", "Al Khaleej", "Al Nada",
    "Al Nakheel", "Al Rawabi", "Al Tazaj", "Al Dana", "Al Manar",
]

SHOP_CATEGORIES = [
    "Grocery", "Mini Market", "Supermarket", "Restaurant", "Cafe", "Bakery",
    "Butchery", "Cold Store", "Hotel Kitchen", "Catering Kitchen",
]

BUSINESS_SUFFIX_BY_CATEGORY = {
    "Grocery": ["Grocery", "Baqala", "Food Store"],
    "Mini Market": ["Mini Market", "Corner Market", "Baqala"],
    "Supermarket": ["Supermarket", "Hyper Mini", "Market"],
    "Restaurant": ["Restaurant", "Kitchen", "Grill"],
    "Cafe": ["Cafe", "Coffee House", "Roastery"],
    "Bakery": ["Bakery", "Sweets & Bakery", "Oven"],
    "Butchery": ["Butchery", "Meat Shop", "Fresh Meat"],
    "Cold Store": ["Cold Store", "Frozen Foods", "Chilled Foods"],
    "Hotel Kitchen": ["Hotel Kitchen", "Hospitality Supplies"],
    "Catering Kitchen": ["Catering Kitchen", "Banquet Kitchen"],
}

VISIT_DAYS = ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"]
ORDER_WINDOWS = ["Morning", "Midday", "Afternoon"]
LIFECYCLE_STATES = ["Active", "New", "At Risk", "Dormant", "Churned"]
LIFECYCLE_PROBS = [0.65, 0.10, 0.15, 0.08, 0.02]

# -----------------------------
# Utility functions
# -----------------------------

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    Faker.seed(seed)


def haversine_km(lat1, lng1, lat2, lng2):
    """Great-circle distance without external geospatial dependencies."""
    r = 6371.0088
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lng2 - lng1)
    a = math.sin(dphi/2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda/2)**2
    return 2 * r * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def jitter_location(lat, lng, radius_km=2.5):
    lat_jitter = np.random.normal(0, radius_km / 111 / 2)
    lng_jitter = np.random.normal(0, radius_km / (111 * np.cos(np.radians(lat))) / 2)
    return float(lat + lat_jitter), float(lng + lng_jitter)


def random_date_between(start, end):
    days = (end - start).days
    return start + timedelta(days=random.randint(0, days))


def weighted_choice(values, probs):
    return random.choices(values, weights=probs, k=1)[0]


def generate_plate(prefix):
    return f"{prefix}{random.choice(string.ascii_uppercase)} {random.randint(1000, 9999)}"


def performance_multiplier():
    bucket = random.random()
    if bucket < 0.15:
        return round(random.uniform(1.10, 1.20), 2)
    if bucket < 0.85:
        return round(random.uniform(0.95, 1.08), 2)
    return round(random.uniform(0.85, 0.94), 2)


def cold_truck_required(category):
    probs = {
        "Cold Store": 1.00,
        "Butchery": 1.00,
        "Hotel Kitchen": 0.80,
        "Catering Kitchen": 0.75,
        "Restaurant": 0.60,
        "Supermarket": 0.45,
        "Bakery": 0.25,
        "Cafe": 0.20,
        "Grocery": 0.12,
        "Mini Market": 0.12,
    }
    return random.random() < probs[category]


def choose_payment_type(volume_tier):
    credit_prob = {"HIGH": 0.75, "MED": 0.45, "LOW": 0.20}[volume_tier]
    return "credit" if random.random() < credit_prob else "cash"


def generate_credit(volume_tier, payment_type, lifecycle_state):
    if payment_type == "cash":
        return 0.0, 0.0
    limit_ranges = {
        "HIGH": (30000, 120000),
        "MED": (10000, 45000),
        "LOW": (2000, 15000),
    }
    credit_limit = round(random.uniform(*limit_ranges[volume_tier]), 2)
    if lifecycle_state in ["At Risk", "Dormant"]:
        pct = random.uniform(0.55, 1.10)
    elif lifecycle_state == "Churned":
        pct = random.uniform(0.70, 1.10)
    else:
        pct = random.choices(
            [random.uniform(0.05, 0.35), random.uniform(0.35, 0.70), random.uniform(0.70, 1.10)],
            weights=[0.65, 0.25, 0.10],
            k=1,
        )[0]
    return credit_limit, round(credit_limit * pct, 2)


def generate_shop_name(category, locality, used_names):
    suffix = random.choice(BUSINESS_SUFFIX_BY_CATEGORY[category])
    include_locality = random.random() < 0.28
    templates = [
        "{prefix} {suffix}",
        "{owner} {suffix}",
        "{prefix} Fresh {suffix}",
        "{owner} Trading {suffix}",
    ]
    if include_locality:
        templates.extend(["{locality} {suffix}", "{prefix} {locality} {suffix}"])

    # Keep cold-chain suffixes aligned with cold-chain categories.
    if suffix in {"Frozen Foods", "Cold Store", "Chilled Foods"} and category != "Cold Store":
        suffix = random.choice(BUSINESS_SUFFIX_BY_CATEGORY[category])

    for _ in range(50):
        name = random.choice(templates).format(
            prefix=random.choice(BUSINESS_PREFIXES),
            owner=random.choice(OWNER_NAMES),
            locality=locality,
            suffix=suffix,
        )
        if name not in used_names:
            used_names.add(name)
            return name
    name = f"{locality} {suffix} {random.randint(100, 999)}"
    used_names.add(name)
    return name

# -----------------------------
# Generator functions
# -----------------------------

def generate_territories():
    df = pd.DataFrame(TERRITORIES).copy()
    df["default_salesperson"] = None
    df["default_van"] = None
    return df[
        ["territory_id", "territory_name", "warehouse_lat", "warehouse_lng", "warehouse_address",
         "center_lat", "center_lng", "radius_km", "default_salesperson", "default_van"]
    ]


def generate_salespeople(territory_df, salespeople_per_territory=3):
    names = SAUDI_SALESPERSON_NAMES.copy()
    random.shuffle(names)
    rows = []
    for _, ter in territory_df.iterrows():
        code = CITY_CODES[ter.territory_id]
        for i in range(1, salespeople_per_territory + 1):
            rows.append({
                "sales_id": f"SAL_{code}_{i:03d}",
                "name": names.pop() if names else fake.name(),
                "territory_id": ter.territory_id,
                "working_hours_per_day": 8.0,
                "shift_start_time": "09:00",
                "assigned_van": None,
                "active_status": random.random() < 0.93,
                "performance_multiplier": performance_multiplier(),
            })
    return pd.DataFrame(rows)


def generate_vans(territory_df, salesperson_df, backup_vans_per_territory=1):
    rows = []
    for _, ter in territory_df.iterrows():
        n_sales = int((salesperson_df["territory_id"] == ter.territory_id).sum())
        total_vans = n_sales + backup_vans_per_territory
        code = CITY_CODES[ter.territory_id]
        prefix = PLATE_PREFIXES[ter.territory_id]
        for i in range(1, total_vans + 1):
            rows.append({
                "van_id": f"VAN_{code}_{i:03d}",
                "registration_no": generate_plate(prefix),
                "cold_truck_enabled": random.random() < 0.50,
                "territory_id": ter.territory_id,
                "active_status": random.random() < 0.96,
            })
    return pd.DataFrame(rows)


def assign_vans_to_salespeople(salesperson_df, van_df):
    salesperson_df = salesperson_df.copy()
    for territory_id in salesperson_df["territory_id"].unique():
        sp_idx = salesperson_df.index[salesperson_df["territory_id"] == territory_id].tolist()
        vans = van_df[van_df["territory_id"] == territory_id]["van_id"].tolist()
        for idx, van_id in zip(sp_idx, vans):
            salesperson_df.loc[idx, "assigned_van"] = van_id
    return salesperson_df


def assign_defaults(territory_df, salesperson_df, van_df):
    territory_df = territory_df.copy()
    for idx, ter in territory_df.iterrows():
        territory_id = ter.territory_id
        active_sp = salesperson_df[(salesperson_df.territory_id == territory_id) & (salesperson_df.active_status)]
        sp_pool = active_sp if not active_sp.empty else salesperson_df[salesperson_df.territory_id == territory_id]
        default_sp = sp_pool.sort_values("performance_multiplier", ascending=False).iloc[0]
        default_van = default_sp.assigned_van
        if pd.isna(default_van):
            default_van = van_df[van_df.territory_id == territory_id].iloc[0].van_id
        territory_df.loc[idx, "default_salesperson"] = default_sp.sales_id
        territory_df.loc[idx, "default_van"] = default_van
    return territory_df


def generate_customers(territory_df, customers_per_territory=100):
    rows = []
    today = date.today()
    start_acq = today - timedelta(days=5 * 365)
    end_acq = today - timedelta(days=30)

    for _, ter in territory_df.iterrows():
        territory_id = ter.territory_id
        code = CITY_CODES[territory_id]
        used_names = set()
        tiers = ["HIGH"] * 20 + ["MED"] * 30 + ["LOW"] * 50
        random.shuffle(tiers)

        for i in range(1, customers_per_territory + 1):
            locality, base_lat, base_lng = random.choice(LOCALITIES[territory_id])
            for _ in range(100):
                lat, lng = jitter_location(base_lat, base_lng, radius_km=2.5)
                if haversine_km(lat, lng, ter.center_lat, ter.center_lng) <= ter.radius_km:
                    break
            else:
                lat, lng = base_lat, base_lng

            tier = tiers[i - 1]
            lifecycle = weighted_choice(LIFECYCLE_STATES, LIFECYCLE_PROBS)
            category = random.choice(SHOP_CATEGORIES)
            payment_type = choose_payment_type(tier)
            credit_limit, outstanding_balance = generate_credit(tier, payment_type, lifecycle)
            customer_rating = int(random.choices([1, 2, 3, 4, 5], weights=[0.05, 0.10, 0.25, 0.35, 0.25], k=1)[0])

            rows.append({
                "customer_id": f"CUS_{code}_{i:04d}",
                "shop_name": generate_shop_name(category, locality, used_names),
                "gps_lat": round(lat, 6),
                "gps_lng": round(lng, 6),
                "locality": locality,
                "territory_id": territory_id,
                "customer_rating": customer_rating,
                "review_rating": round(float(np.clip(np.random.normal(4.0, 0.55), 2.5, 5.0)), 1),
                "shop_category": category,
                "cold_truck_required": cold_truck_required(category),
                "volume_tier": tier,
                "payment_type": payment_type,
                "credit_limit": credit_limit,
                "outstanding_balance": outstanding_balance,
                "lifecycle_state": lifecycle,
                "acquisition_date": random_date_between(start_acq, end_acq),
                "preferred_visit_day": random.choice(VISIT_DAYS),
                "preferred_order_window": random.choice(ORDER_WINDOWS),
            })
    return pd.DataFrame(rows)


def fridays_between(start_date, end_date):
    cur = start_date
    while cur.weekday() != 4:  # Monday=0, Friday=4
        cur += timedelta(days=1)
    while cur <= end_date:
        yield cur
        cur += timedelta(days=7)


def generate_holidays(territory_df, salesperson_df, van_df, months=3):
    rows = []
    today = date.today()
    start = date(today.year, today.month, 1)
    end = start + timedelta(days=months * 31)
    holiday_id = 1

    # Territory Friday closure rows
    for _, ter in territory_df.iterrows():
        for d in fridays_between(start, end):
            rows.append({
                "holiday_id": f"HOL_{holiday_id:05d}",
                "salesperson_holiday": None,
                "van_holiday": None,
                "territory_holiday": ter.territory_id,
                "from_date": d,
                "to_date": d,
                "reason": "Friday closure",
            })
            holiday_id += 1

        # Common Saudi master calendar events. Dates are approximate placeholders for synthetic data.
        for label, offset_days, duration_days in [
            ("Ramadan adjusted operating hours", 10, 29),
            ("Eid Al-Fitr holiday", 40, 4),
            ("Saudi National Day", 145, 1),
        ]:
            from_d = start + timedelta(days=offset_days)
            to_d = from_d + timedelta(days=duration_days - 1)
            rows.append({
                "holiday_id": f"HOL_{holiday_id:05d}",
                "salesperson_holiday": None,
                "van_holiday": None,
                "territory_holiday": ter.territory_id,
                "from_date": from_d,
                "to_date": to_d,
                "reason": label,
            })
            holiday_id += 1

    # Salesperson leave: 1-2 short leaves each
    for _, sp in salesperson_df.iterrows():
        for _ in range(random.randint(1, 2)):
            from_d = random_date_between(start, end)
            duration = random.choice([1, 1, 2, 3])
            rows.append({
                "holiday_id": f"HOL_{holiday_id:05d}",
                "salesperson_holiday": sp.sales_id,
                "van_holiday": None,
                "territory_holiday": None,
                "from_date": from_d,
                "to_date": from_d + timedelta(days=duration - 1),
                "reason": random.choice(["Annual leave", "Sick leave"]),
            })
            holiday_id += 1

    # Van maintenance: 1 maintenance day per van per month
    for _, van in van_df.iterrows():
        for month_offset in range(months):
            month_start = start + timedelta(days=month_offset * 31)
            from_d = month_start + timedelta(days=random.randint(0, 27))
            rows.append({
                "holiday_id": f"HOL_{holiday_id:05d}",
                "salesperson_holiday": None,
                "van_holiday": van.van_id,
                "territory_holiday": None,
                "from_date": from_d,
                "to_date": from_d,
                "reason": "Van maintenance",
            })
            holiday_id += 1

    return pd.DataFrame(rows)


def generate_config():
    values = {
        "avg_speed_kmh": 32,
        "avg_service_time_min": 22,
        "buffer_pct": 0.15,
        "rfm_window_days": 90,
        "route_partial_prob": 0.08,
        "route_cancel_prob": 0.03,
        "traffic_jam_prob": 0.12,
        "credit_outstanding_cap": 0.85,
        "normal_shift_start_time": "09:00",
        "ramadan_shift_start_time": "10:00",
    }
    return pd.DataFrame([{"config_key": k, "config_value": v} for k, v in values.items()])


def score_from_quantiles(series, higher_is_better=True):
    # qcut can fail on repeated values, so rank first for stable 1-5 scores.
    ranks = series.rank(method="first")
    labels = [1, 2, 3, 4, 5]
    scored = pd.qcut(ranks, q=5, labels=labels).astype(int)
    if not higher_is_better:
        scored = 6 - scored
    return scored


def generate_rfm_scores(customer_df):
    rows = []
    for _, c in customer_df.iterrows():
        tier = c.volume_tier
        lifecycle = c.lifecycle_state

        if tier == "HIGH":
            recency = random.randint(1, 20)
            frequency = random.randint(20, 50)
            monetary = random.uniform(25000, 180000)
        elif tier == "MED":
            recency = random.randint(7, 45)
            frequency = random.randint(8, 25)
            monetary = random.uniform(7000, 55000)
        else:
            recency = random.randint(20, 90)
            frequency = random.randint(1, 12)
            monetary = random.uniform(500, 12000)

        if lifecycle == "New":
            recency = random.randint(1, 14)
            frequency = max(1, int(frequency * random.uniform(0.25, 0.55)))
            monetary *= random.uniform(0.25, 0.60)
        elif lifecycle == "At Risk":
            recency = max(recency, random.randint(45, 100))
            frequency = max(1, int(frequency * random.uniform(0.45, 0.85)))
            monetary *= random.uniform(0.60, 1.00)
        elif lifecycle == "Dormant":
            recency = random.randint(90, 180)
            frequency = max(0, int(frequency * random.uniform(0.10, 0.35)))
            monetary *= random.uniform(0.10, 0.35)
        elif lifecycle == "Churned":
            recency = random.randint(181, 365)
            frequency = random.choice([0, 0, 1])
            monetary *= random.uniform(0.00, 0.10)

        rows.append({
            "customer_id": c.customer_id,
            "recency": int(recency),
            "frequency": int(frequency),
            "monetary": round(float(monetary), 2),
        })

    df = pd.DataFrame(rows)
    df["r_score"] = score_from_quantiles(df["recency"], higher_is_better=False)
    df["f_score"] = score_from_quantiles(df["frequency"], higher_is_better=True)
    df["m_score"] = score_from_quantiles(df["monetary"], higher_is_better=True)
    df["rfm_score"] = df["r_score"].astype(str) + df["f_score"].astype(str) + df["m_score"].astype(str)

    def segment(row):
        r, f, m = row.r_score, row.f_score, row.m_score
        if r >= 4 and f >= 4 and m >= 4:
            return "Champion"
        if f >= 4 and m >= 3:
            return "Loyal"
        if r >= 4 and f in [2, 3]:
            return "Potential Loyalist"
        if r <= 2 and f >= 3:
            return "At Risk"
        if r <= 2 and f <= 2 and m <= 2:
            return "Hibernating"
        return "Need Attention"

    df["segment"] = df.apply(segment, axis=1)
    return df

# -----------------------------
# Validation and reporting
# -----------------------------

def assert_fk(child_df, child_col, parent_df, parent_col):
    missing = set(child_df[child_col].dropna()) - set(parent_df[parent_col])
    assert not missing, f"Broken FK {child_col}: {missing}"


def validate_all(territory_df, salesperson_df, van_df, customer_df, holiday_df, config_df, rfm_scores_df):
    # Foreign keys
    assert_fk(customer_df, "territory_id", territory_df, "territory_id")
    assert_fk(salesperson_df, "territory_id", territory_df, "territory_id")
    assert_fk(van_df, "territory_id", territory_df, "territory_id")
    assert_fk(holiday_df, "territory_holiday", territory_df, "territory_id")
    assert_fk(holiday_df, "salesperson_holiday", salesperson_df, "sales_id")
    assert_fk(holiday_df, "van_holiday", van_df, "van_id")
    assert_fk(rfm_scores_df, "customer_id", customer_df, "customer_id")

    # Primary keys
    assert territory_df["territory_id"].is_unique
    assert salesperson_df["sales_id"].is_unique
    assert van_df["van_id"].is_unique
    assert customer_df["customer_id"].is_unique
    assert holiday_df["holiday_id"].is_unique
    assert rfm_scores_df["customer_id"].is_unique

    # Row counts
    assert len(territory_df) == 3
    assert len(customer_df) == 300
    assert 6 <= len(salesperson_df) <= 9
    assert 9 <= len(van_df) <= 12
    assert len(rfm_scores_df) == 300

    # Same territory checks
    van_territory = van_df.set_index("van_id")["territory_id"].to_dict()
    sp_territory = salesperson_df.set_index("sales_id")["territory_id"].to_dict()
    for _, sp in salesperson_df.iterrows():
        assert van_territory[sp.assigned_van] == sp.territory_id
    for _, ter in territory_df.iterrows():
        assert sp_territory[ter.default_salesperson] == ter.territory_id
        assert van_territory[ter.default_van] == ter.territory_id

    # Business rules
    cash = customer_df["payment_type"] == "cash"
    assert (customer_df.loc[cash, "credit_limit"] == 0).all()
    assert (customer_df.loc[cash, "outstanding_balance"] == 0).all()
    credit = customer_df["payment_type"] == "credit"
    assert (customer_df.loc[credit, "credit_limit"] > 0).all()
    assert customer_df.loc[customer_df.shop_category.isin(["Cold Store", "Butchery"]), "cold_truck_required"].all()

    # Customer coordinates inside territory radius
    ter_lookup = territory_df.set_index("territory_id")
    for _, c in customer_df.iterrows():
        ter = ter_lookup.loc[c.territory_id]
        dist = haversine_km(c.gps_lat, c.gps_lng, ter.center_lat, ter.center_lng)
        assert dist <= ter.radius_km + 1e-6, f"Customer outside radius: {c.customer_id} {dist:.2f}km"

    # No duplicate shop names inside territory
    dupes = customer_df.duplicated(subset=["territory_id", "shop_name"]).sum()
    assert dupes == 0, f"Duplicate shop names inside territory: {dupes}"

    # Tier distribution
    tier_counts = customer_df.groupby(["territory_id", "volume_tier"]).size().unstack(fill_value=0)
    for territory_id in territory_df["territory_id"]:
        assert int(tier_counts.loc[territory_id, "HIGH"]) == 20
        assert int(tier_counts.loc[territory_id, "MED"]) == 30
        assert int(tier_counts.loc[territory_id, "LOW"]) == 50

    return True


def data_quality_report(territory_df, salesperson_df, van_df, customer_df, holiday_df, config_df, rfm_scores_df):
    report = {
        "row_counts": {
            "territory": len(territory_df),
            "salesperson": len(salesperson_df),
            "van": len(van_df),
            "customer": len(customer_df),
            "holiday": len(holiday_df),
            "config": len(config_df),
            "rfm_scores": len(rfm_scores_df),
        },
        "customer_tiers_by_territory": customer_df.groupby(["territory_id", "volume_tier"]).size().unstack(fill_value=0).to_dict(orient="index"),
        "lifecycle_distribution": customer_df["lifecycle_state"].value_counts(normalize=True).round(3).to_dict(),
        "payment_type_distribution": customer_df["payment_type"].value_counts(normalize=True).round(3).to_dict(),
        "cold_truck_required_share": round(float(customer_df["cold_truck_required"].mean()), 3),
        "rfm_segments": rfm_scores_df["segment"].value_counts().to_dict(),
        "validation_status": "passed",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
    }
    return report


def generate_all(seed=42, output_dir="saudi_master_data_output", write_files=True):
    set_seed(seed)

    territory_df = generate_territories()
    salesperson_df = generate_salespeople(territory_df)
    van_df = generate_vans(territory_df, salesperson_df)
    salesperson_df = assign_vans_to_salespeople(salesperson_df, van_df)
    territory_df = assign_defaults(territory_df, salesperson_df, van_df)
    customer_df = generate_customers(territory_df)
    holiday_df = generate_holidays(territory_df, salesperson_df, van_df)
    config_df = generate_config()
    rfm_scores_df = generate_rfm_scores(customer_df)

    validate_all(territory_df, salesperson_df, van_df, customer_df, holiday_df, config_df, rfm_scores_df)
    report = data_quality_report(territory_df, salesperson_df, van_df, customer_df, holiday_df, config_df, rfm_scores_df)

    outputs = {
        "territory": territory_df,
        "salesperson": salesperson_df,
        "van": van_df,
        "customer": customer_df,
        "holiday": holiday_df,
        "config": config_df,
        "rfm_scores": rfm_scores_df,
    }

    if write_files:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        for name, df in outputs.items():
            df.to_csv(out / f"{name}.csv", index=False)
        with open(out / "data_quality_report.json", "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, default=str, ensure_ascii=False)
        print(f"Wrote CSV/JSON outputs to: {out.resolve()}")

    return outputs, report

# Generate data
outputs, report = generate_all(seed=42)
territory_df = outputs["territory"]
salesperson_df = outputs["salesperson"]
van_df = outputs["van"]
customer_df = outputs["customer"]
holiday_df = outputs["holiday"]
config_df = outputs["config"]
rfm_scores_df = outputs["rfm_scores"]

print(json.dumps(report, indent=2, default=str, ensure_ascii=False))

Wrote CSV/JSON outputs to: D:\Data Science\Basamh\JP\journey-planner\saudi_master_data_output
{
  "row_counts": {
    "territory": 3,
    "salesperson": 9,
    "van": 12,
    "customer": 300,
    "holiday": 98,
    "config": 10,
    "rfm_scores": 300
  },
  "customer_tiers_by_territory": {
    "TER_DMM": {
      "HIGH": 20,
      "LOW": 50,
      "MED": 30
    },
    "TER_JED": {
      "HIGH": 20,
      "LOW": 50,
      "MED": 30
    },
    "TER_RUH": {
      "HIGH": 20,
      "LOW": 50,
      "MED": 30
    }
  },
  "lifecycle_distribution": {
    "Active": 0.65,
    "New": 0.123,
    "At Risk": 0.12,
    "Dormant": 0.103,
    "Churned": 0.003
  },
  "payment_type_distribution": {
    "cash": 0.637,
    "credit": 0.363
  },
  "cold_truck_required_share": 0.523,
  "rfm_segments": {
    "Need Attention": 76,
    "Champion": 69,
    "Hibernating": 47,
    "Loyal": 41,
    "At Risk": 37,
    "Potential Loyalist": 30
  },
  "validation_status": "passed",
  "generated_at": "2026-05-27T15:15:17"
}


## Preview generated tables

Run the cells below after generation to inspect samples and distribution checks.

In [17]:
holiday_df[holiday_df["salesperson_holiday"].notna()]

,holiday_id,salesperson_holiday,van_holiday,territory_holiday,from_date,to_date,reason
51,HOL_00052,SAL_RUH_001,NaN,NaN,2026-07-03,2026-07-03,Annual leave
52,HOL_00053,SAL_RUH_002,NaN,NaN,2026-06-03,2026-06-03,Annual leave
53,HOL_00054,SAL_RUH_003,NaN,NaN,2026-06-01,2026-06-02,Annual leave
54,HOL_00055,SAL_JED_001,NaN,NaN,2026-05-16,2026-05-16,Sick leave
55,HOL_00056,SAL_JED_002,NaN,NaN,2026-07-09,2026-07-09,Sick leave
56,HOL_00057,SAL_JED_003,NaN,NaN,2026-07-19,2026-07-20,Sick leave
57,HOL_00058,SAL_JED_003,NaN,NaN,2026-07-13,2026-07-14,Sick leave
58,HOL_00059,SAL_DMM_001,NaN,NaN,2026-07-05,2026-07-06,Sick leave
59,HOL_00060,SAL_DMM_002,NaN,NaN,2026-07-13,2026-07-13,Annual leave
60,HOL_00061,SAL_DMM_003,NaN,NaN,2026-07-01,2026-07-01,Sick leave
61,HOL_00062,SAL_DMM_003,NaN,NaN,2026-06-20,2026-06-20,Sick leave

In [18]:

print("Territories")
display(territory_df)

print("Salespeople")
display(salesperson_df.head(10))

print("Vans")
display(van_df.head(10))

print("Customers")
display(customer_df.head(10))

print("RFM scores")
display(rfm_scores_df.head(10))

Territories

,territory_id,territory_name,warehouse_lat,warehouse_lng,warehouse_address,center_lat,center_lng,radius_km,default_salesperson,default_van
0,TER_RUH,Riyadh Central,24.5790,46.8237,"Industrial Area, Riyadh",24.7136,46.6753,25,SAL_RUH_001,VAN_RUH_001
1,TER_JED,Jeddah North,21.3429,39.2357,"Al Khomrah Logistics Area, Jeddah",21.5433,39.1728,22,SAL_JED_002,VAN_JED_002
2,TER_DMM,Dammam Metro,26.2926,50.1629,"2nd Industrial City, Dammam",26.4207,50.0888,20,SAL_DMM_002,VAN_DMM_002

Salespeople

,sales_id,name,territory_id,working_hours_per_day,shift_start_time,assigned_van,active_status,performance_multiplier
0,SAL_RUH_001,Arif Rahman,TER_RUH,8.0,09:00,VAN_RUH_001,True,1.04
1,SAL_RUH_002,Nasser Al-Dossari,TER_RUH,8.0,09:00,VAN_RUH_002,True,0.99
2,SAL_RUH_003,Abdullah Al-Qahtani,TER_RUH,8.0,09:00,VAN_RUH_003,True,0.97
3,SAL_JED_001,Ahmed Al-Anazi,TER_JED,8.0,09:00,VAN_JED_001,True,0.98
4,SAL_JED_002,Majed Al-Shammari,TER_JED,8.0,09:00,VAN_JED_002,True,1.14
5,SAL_JED_003,Imran Ahmed,TER_JED,8.0,09:00,VAN_JED_003,True,0.98
6,SAL_DMM_001,Khalid Al-Ghamdi,TER_DMM,8.0,09:00,VAN_DMM_001,True,0.97
7,SAL_DMM_002,Hassan Al-Yami,TER_DMM,8.0,09:00,VAN_DMM_002,True,1.13
8,SAL_DMM_003,Fahad Al-Otaibi,TER_DMM,8.0,09:00,VAN_DMM_003,True,0.88

Vans

        van_id registration_no  cold_truck_enabled territory_id  active_status
0  VAN_RUH_001        RUG 2139                True      TER_RUH           True
1  VAN_RUH_002        RUJ 2307               False      TER_RUH           True
2  VAN_RUH_003        RUM 5554                True      TER_RUH           True
3  VAN_RUH_004        RUF 7065                True      TER_RUH           True
4  VAN_JED_001        JEW 2169               False      TER_JED           True
5  VAN_JED_002        JEX 5010                True      TER_JED           True
6  VAN_JED_003        JEU 4598               False      TER_JED           True
7  VAN_JED_004        JEY 1916                True      TER_JED           True
8  VAN_DMM_001        DMK 7572                True      TER_DMM           True
9  VAN_DMM_002        DMS 6155                True      TER_DMM           True

Customers

,customer_id,shop_name,gps_lat,gps_lng,locality,territory_id,customer_rating,review_rating,shop_category,cold_truck_required,volume_tier,payment_type,credit_limit,outstanding_balance,lifecycle_state,acquisition_date,preferred_visit_day,preferred_order_window
0,CUS_RUH_0001,Al Waha Fresh Mini Market,24.769194,46.600485,Hittin,TER_RUH,2,4.4,Mini Market,False,LOW,cash,0.00,0.00,Active,2025-02-26,Tuesday,Morning
1,CUS_RUH_0002,Al Othman Banquet Kitchen,24.780751,46.599296,Hittin,TER_RUH,3,3.9,Catering Kitchen,True,MED,cash,0.00,0.00,Active,2023-05-23,Tuesday,Midday
2,CUS_RUH_0003,Al Qassim Al Yasmin Grocery,24.844884,46.639722,Al Yasmin,TER_RUH,5,3.7,Grocery,False,MED,cash,0.00,0.00,At Risk,2022-10-19,Sunday,Morning
3,CUS_RUH_0004,Al Waha Fresh Meat,24.769710,46.596453,Hittin,TER_RUH,2,3.7,Butchery,True,HIGH,credit,71636.53,26962.89,Active,2022-09-24,Sunday,Midday
4,CUS_RUH_0005,Al Manar Fresh Butchery,24.829825,46.606460,Al Yasmin,TER_RUH,3,3.1,Butchery,True,MED,cash,0.00,0.00,Active,2023-01-02,Tuesday,Afternoon
5,CUS_RUH_0006,Al Shammari Chilled Foods,24.757268,46.589639,Hittin,TER_RUH,2,4.2,Cold Store,True,LOW,credit,5857.20,3237.35,New,2022-06-12,Saturday,Afternoon
6,CUS_RUH_0007,Olaya Grill,24.701275,46.657092,Olaya,TER_RUH,5,4.8,Restaurant,True,LOW,cash,0.00,0.00,New,2025-02-02,Wednesday,Afternoon
7,CUS_RUH_0008,Hittin Cafe,24.761057,46.603037,Hittin,TER_RUH,3,3.2,Cafe,True,MED,credit,35066.71,4264.31,Active,2022-08-07,Wednesday,Midday
8,CUS_RUH_0009,Al Nada Fresh Mini Market,24.661470,46.736475,Al Malaz,TER_RUH,3,3.4,Mini Market,False,LOW,cash,0.00,0.00,Dormant,2021-06-13,Thursday,Afternoon
9,CUS_RUH_0010,Al Ghamdi Mini Market,24.705431,46.703755,Al Sulaymaniyah,TER_RUH,2,3.8,Mini Market,False,MED,cash,0.00,0.00,Dormant,2025-06-05,Monday,Morning

RFM scores

,customer_id,recency,frequency,monetary,r_score,f_score,m_score,rfm_score,segment
0,CUS_RUH_0001,71,5,5683.38,2,2,2,222,Hibernating
1,CUS_RUH_0002,43,12,54005.08,3,4,5,345,Loyal
2,CUS_RUH_0003,96,5,32151.46,1,2,4,124,Need Attention
3,CUS_RUH_0004,13,26,47605.78,4,5,5,455,Champion
4,CUS_RUH_0005,16,23,45672.08,4,5,5,455,Champion
5,CUS_RUH_0006,14,3,2728.57,4,1,1,411,Need Attention
6,CUS_RUH_0007,9,4,1053.56,5,2,1,521,Potential Loyalist
7,CUS_RUH_0008,13,13,9881.75,4,4,3,443,Loyal
8,CUS_RUH_0009,102,1,1863.86,1,1,1,111,Hibernating
9,CUS_RUH_0010,122,3,6879.02,1,1,2,112,Hibernating

In [19]:

print("Tier counts per territory")
display(customer_df.groupby(["territory_id", "volume_tier"]).size().unstack(fill_value=0))

print("Lifecycle distribution")
display(customer_df["lifecycle_state"].value_counts(normalize=True).rename("share").round(3))

print("RFM segments")
display(rfm_scores_df["segment"].value_counts())

print("Output files")
for path in sorted(Path("saudi_master_data_output").glob("*")):
    print(path)

Tier counts per territory

volume_tier   HIGH  LOW  MED
territory_id
TER_DMM         20   50   30
TER_JED         20   50   30
TER_RUH         20   50   30

Lifecycle distribution

lifecycle_state
Active     0.650
New        0.123
At Risk    0.120
Dormant    0.103
Churned    0.003
Name: share, dtype: float64

RFM segments

segment
Need Attention        76
Champion              69
Hibernating           47
Loyal                 41
At Risk               37
Potential Loyalist    30
Name: count, dtype: int64

Output files
saudi_master_data_output\config.csv
saudi_master_data_output\customer.csv
saudi_master_data_output\data_quality_report.json
saudi_master_data_output\holiday.csv
saudi_master_data_output\rfm_scores.csv
saudi_master_data_output\salesperson.csv
saudi_master_data_output\territory.csv
saudi_master_data_output\van.csv


## Notes

- This notebook intentionally excludes route, visit, and basket-level transaction tables.
- The holiday dates are synthetic placeholders suitable for master-data demos. For production Saudi holiday calendars, replace those placeholder rows with an official calendar source.
- `generate_all(seed=42)` is deterministic for repeatable demos. Change the seed to create a different synthetic dataset.

In [24]:
from saudi_multi_salesperson_scheduler import MultiSalespersonScheduler

result = MultiSalespersonScheduler().create_schedules(
    customer_df=customer_df,
    rfm_scores_df=rfm_scores_df,
    salesperson_df=salesperson_df,
    holiday_df=holiday_df,
    territory_df=territory_df,
    config_df=config_df,
    van_df=van_df,
    month_start_date="2026-07-01",
)

Status: OPTIMAL
Objective value: 101879093.0
Best bound: 101879093.0
Status: OPTIMAL
Objective value: 43551226.0
Best bound: 43551226.0
Status: OPTIMAL
Objective value: 94784177.0
Best bound: 94784177.0
Status: OPTIMAL
Objective value: 50452288.0
Best bound: 50452288.0
Status: OPTIMAL
Objective value: 75730195.0
Best bound: 75730195.0
Status: OPTIMAL
Objective value: 45370236.0
Best bound: 45370236.0
Status: OPTIMAL
Objective value: 81771369.0
Best bound: 81771369.0
Status: OPTIMAL
Objective value: 80775472.0
Best bound: 80775472.0
Status: OPTIMAL
Objective value: 91874445.0
Best bound: 91874445.0

In [25]:
display(result)

MultiScheduleResult(detailed_schedule=    schedule_date     sales_id territory_id   customer_id  \
0      2026-07-01  SAL_DMM_001      TER_DMM  CUS_DMM_0012
1      2026-07-01  SAL_DMM_001      TER_DMM  CUS_DMM_0032
2      2026-07-01  SAL_DMM_001      TER_DMM  CUS_DMM_0047
3      2026-07-01  SAL_DMM_001      TER_DMM  CUS_DMM_0080
4      2026-07-01  SAL_DMM_001      TER_DMM  CUS_DMM_0096
..            ...          ...          ...           ...
655    2026-07-27  SAL_RUH_003      TER_RUH  CUS_RUH_0080
656    2026-07-28  SAL_RUH_003      TER_RUH  CUS_RUH_0002
657    2026-07-28  SAL_RUH_003      TER_RUH  CUS_RUH_0005
658    2026-07-30  SAL_RUH_003      TER_RUH  CUS_RUH_0051
659    2026-07-30  SAL_RUH_003      TER_RUH  CUS_RUH_0088

                               shop_name      locality    gps_lat    gps_lng  \
0                Al Riyadh Corner Market    Al Badiyah  26.397293  50.045975
1                    Al Saleh Fresh Meat  Al Mazruiyah  26.455036  50.103660
2               Al Anazi Trading Grocery      Al Shati  26.488855  50.125161
3               Al Dana Fresh Food Store  Al Mazruiyah  26.436857  50.108580
4                      Al Manar Butchery    Al Badiyah  26.422896  50.066042
..                                   ...           ...        ...        ...
655  Al Noor Hittin Hospitality Supplies        Hittin  24.765700  46.593993
656            Al Othman Banquet Kitchen        Hittin  24.780751  46.599296
657              Al Manar Fresh Butchery     Al Yasmin  24.829825  46.606460
658      Al Shehri Trading Chilled Foods     Al Yasmin  24.829921  46.634499
659             Al Zahrani Hotel Kitchen         Olaya  24.710830  46.634420

                segment lifecycle_state  cold_truck_required  \
0              Champion          Active                False
1           Hibernating         Dormant                 True
2              Champion          Active                False
3              Champion          Active                False
4               At Risk          Active                 True
..                  ...             ...                  ...
655      Need Attention             New                 True
656               Loyal          Active                 True
657            Champion          Active                 True
658      Need Attention         At Risk                 True
659  Potential Loyalist          Active                 True

     estimated_visit_minutes  estimated_travel_minutes
0                         22                        61
1                         22                        71
2                         22                        83
3                         22                        63
4                         22                        65
..                       ...                       ...
655                       22                       116
656                       22                       119
657                       22                       133
658                       22                       126
659                       22                        90

[660 rows x 13 columns], daily_schedule=    schedule_date     sales_id territory_id  \
0      2026-07-01  SAL_DMM_001      TER_DMM
1      2026-07-02  SAL_DMM_001      TER_DMM
2      2026-07-04  SAL_DMM_001      TER_DMM
3      2026-07-07  SAL_DMM_001      TER_DMM
4      2026-07-08  SAL_DMM_001      TER_DMM
..            ...          ...          ...
196    2026-07-25  SAL_RUH_003      TER_RUH
197    2026-07-26  SAL_RUH_003      TER_RUH
198    2026-07-27  SAL_RUH_003      TER_RUH
199    2026-07-28  SAL_RUH_003      TER_RUH
200    2026-07-30  SAL_RUH_003      TER_RUH

                                         customer_list  customer_count  \
0    [CUS_DMM_0012, CUS_DMM_0096, CUS_DMM_0080, CUS...               5
1    [CUS_DMM_0064, CUS_DMM_0082, CUS_DMM_0008, CUS...               5
2    [CUS_DMM_0082, CUS_DMM_0044, CUS_DMM_0053, CUS...               5
3    [CUS_DMM_0051, CUS_DMM_0019, CUS_DMM_0098, CUS...               5
4    [CUS_DMM_0012, CUS_DMM_0096, CUS_DMM_0066, CUS...               5
..                                                 ...             ...
196                       [CUS_RUH_0006, CUS_RUH_0041]               2
197  [CUS_RUH_0035, CUS_RUH_0092, CUS_RUH_0055, CUS...               4
198  [CUS_RUH_0061, CUS_RUH_0020, CUS_RUH_0080, CUS...               4
199                       [CUS_RUH_0002, CUS_RUH_0005]               2
200                       [CUS_RUH_0088, CUS_RUH_0051]               2

                                           route_order  total_visit_min  \
0    [Al Riyadh Corner Market, Al Manar Butchery, A...              110
1    [Al Tazaj Market, Al Badiyah Grocery, Al Jazee...              110
2    [Al Badiyah Grocery, Al Madina Fresh Corner Ma...              110
3    [Al Subaie Trading Bakery, Al Tazaj Hospitalit...              110
4    [Al Riyadh Corner Market, Al Manar Butchery, A...              110
..                                                 ...              ...
196  [Al Shammari Chilled Foods, Al Baraka Mini Mar...               44
197  [Al Malki Trading Catering Kitchen, Al Tazaj F...               88
198  [Al Manar Fresh Hospitality Supplies, Al Madin...               88
199  [Al Othman Banquet Kitchen, Al Manar Fresh But...               44
200  [Al Zahrani Hotel Kitchen, Al Shehri Trading C...               44

     total_travel_min
0                 343
1                 347
2                 344
3                 349
4                 349
..                ...
196               234
197               340
198               361
199               252
200               216

[201 rows x 8 columns], salesperson_results={'SAL_RUH_001': SalespersonScheduleResult(sales_id='SAL_RUH_001', territory_id='TER_RUH', detailed_schedule=    schedule_date     sales_id territory_id   customer_id  \
0      2026-07-01  SAL_RUH_001      TER_RUH  CUS_RUH_0007
1      2026-07-01  SAL_RUH_001      TER_RUH  CUS_RUH_0008
2      2026-07-01  SAL_RUH_001      TER_RUH  CUS_RUH_0049
3      2026-07-01  SAL_RUH_001      TER_RUH  CUS_RUH_0067
4      2026-07-02  SAL_RUH_001      TER_RUH  CUS_RUH_0018
..            ...          ...          ...           ...
96     2026-07-29  SAL_RUH_001      TER_RUH  CUS_RUH_0063
97     2026-07-29  SAL_RUH_001      TER_RUH  CUS_RUH_0073
98     2026-07-29  SAL_RUH_001      TER_RUH  CUS_RUH_0083
99     2026-07-30  SAL_RUH_001      TER_RUH  CUS_RUH_0023
100    2026-07-30  SAL_RUH_001      TER_RUH  CUS_RUH_0084

                           shop_name         locality    gps_lat    gps_lng  \
0                        Olaya Grill            Olaya  24.701275  46.657092
1                        Hittin Cafe           Hittin  24.761057  46.603037
2          Al Shammari Corner Market            Olaya  24.714427  46.684292
3                Al Noor Mini Market  Al Sulaymaniyah  24.701856  46.697032
4                   Al Rawabi Baqala         Al Malaz  24.663263  46.726712
..                               ...              ...        ...        ...
96        Al Waha Fresh Frozen Foods  Al Sulaymaniyah  24.706529  46.710297
97             Al Rawabi Mini Market        Al Yasmin  24.818397  46.627262
98                  Al Baraka Bakery           Hittin  24.758252  46.594098
99         Al Tazaj Fresh Restaurant        Al Yasmin  24.826289  46.642652
100  Al Baraka Fresh Banquet Kitchen        Al Yasmin  24.831661  46.614555

                segment lifecycle_state  cold_truck_required  \
0    Potential Loyalist             New                 True
1                 Loyal          Active                 True
2              Champion          Active                False
3              Champion          Active                False
4               At Risk          Active                False
..                  ...             ...                  ...
96       Need Attention          Active                 True
97             Champion          Active                False
98   Potential Loyalist          Active                False
99                Loyal          Active                 True
100      Need Attention             New                 True

     estimated_visit_minutes  estimated_travel_minutes
0                         22                        81
1                         22                       112
2                         22                        77
3                         22                        70
4                         22                        50
..                       ...                       ...
96                        22                        68
97                        22                       124
98                        22                       114
99                        22                       123
100                       22                       131

[101 rows x 13 columns], daily_schedule=   schedule_date     sales_id territory_id  \
0     2026-07-01  SAL_RUH_001      TER_RUH
1     2026-07-02  SAL_RUH_001      TER_RUH
2     2026-07-04  SAL_RUH_001      TER_RUH
3     2026-07-05  SAL_RUH_001      TER_RUH
4     2026-07-06  SAL_RUH_001      TER_RUH
5     2026-07-07  SAL_RUH_001      TER_RUH
6     2026-07-08  SAL_RUH_001      TER_RUH
7     2026-07-09  SAL_RUH_001      TER_RUH
8     2026-07-11  SAL_RUH_001      TER_RUH
9     2026-07-12  SAL_RUH_001      TER_RUH
10    2026-07-13  SAL_RUH_001      TER_RUH
11    2026-07-14  SAL_RUH_001      TER_RUH
12    2026-07-15  SAL_RUH_001      TER_RUH
13    2026-07-16  SAL_RUH_001      TER_RUH
14    2026-07-18  SAL_RUH_001      TER_RUH
15    2026-07-19  SAL_RUH_001      TER_RUH
16    2026-07-20  SAL_RUH_001      TER_RUH
17    2026-07-21  SAL_RUH_001      TER_RUH
18    2026-07-22  SAL_RUH_001      TER_RUH
19    2026-07-23  SAL_RUH_001      TER_RUH
20    2026-07-25  SAL_RUH_001      TER_RUH
21    2026-07-26  SAL_RUH_001      TER_RUH
22    2026-07-27  SAL_RUH_001      TER_RUH
23    2026-07-28  SAL_RUH_001      TER_RUH
24    2026-07-29  SAL_RUH_001      TER_RUH
25    2026-07-30  SAL_RUH_001      TER_RUH

                                        customer_list  customer_count  \
0   [CUS_RUH_0067, CUS_RUH_0049, CUS_RUH_0007, CUS...               4
1   [CUS_RUH_0018, CUS_RUH_0087, CUS_RUH_0078, CUS...               4
2   [CUS_RUH_0070, CUS_RUH_0054, CUS_RUH_0030, CUS...               4
3   [CUS_RUH_0090, CUS_RUH_0029, CUS_RUH_0004, CUS...               4
4   [CUS_RUH_0094, CUS_RUH_0099, CUS_RUH_0027, CUS...               4
5   [CUS_RUH_0021, CUS_RUH_0049, CUS_RUH_0093, CUS...               4
6   [CUS_RUH_0075, CUS_RUH_0067, CUS_RUH_0049, CUS...               4
7   [CUS_RUH_0028, CUS_RUH_0022, CUS_RUH_0097, CUS...               4
8   [CUS_RUH_0070, CUS_RUH_0054, CUS_RUH_0065, CUS...               4
9   [CUS_RUH_0090, CUS_RUH_0029, CUS_RUH_0037, CUS...               4
10  [CUS_RUH_0012, CUS_RUH_0099, CUS_RUH_0047, CUS...               4
11  [CUS_RUH_0021, CUS_RUH_0100, CUS_RUH_0069, CUS...               4
12  [CUS_RUH_0043, CUS_RUH_0007, CUS_RUH_0008, CUS...               4
13  [CUS_RUH_0009, CUS_RUH_0018, CUS_RUH_0097, CUS...               4
14  [CUS_RUH_0054, CUS_RUH_0030, CUS_RUH_0065, CUS...               4
15  [CUS_RUH_0090, CUS_RUH_0029, CUS_RUH_0004, CUS...               4
16  [CUS_RUH_0094, CUS_RUH_0043, CUS_RUH_0008, CUS...               4
17  [CUS_RUH_0021, CUS_RUH_0067, CUS_RUH_0093, CUS...               4
18  [CUS_RUH_0043, CUS_RUH_0063, CUS_RUH_0067, CUS...               4
19  [CUS_RUH_0050, CUS_RUH_0022, CUS_RUH_0097, CUS...               4
20  [CUS_RUH_0021, CUS_RUH_0054, CUS_RUH_0076, CUS...               4
21  [CUS_RUH_0090, CUS_RUH_0037, CUS_RUH_0004, CUS...               4
22  [CUS_RUH_0012, CUS_RUH_0047, CUS_RUH_0044, CUS...               4
23         [CUS_RUH_0093, CUS_RUH_0056, CUS_RUH_0026]               3
24  [CUS_RUH_0063, CUS_RUH_0049, CUS_RUH_0083, CUS...               4
25                       [CUS_RUH_0023, CUS_RUH_0084]               2

                                          route_order  total_visit_min  \
0   [Al Noor Mini Market, Al Shammari Corner Marke...               88
1   [Al Rawabi Baqala, Al Nakheel Fresh Hyper Mini...               88
2   [Al Khaleej Al Sulaymaniyah Baqala, Al Manar A...               88
3   [Al Nakheel Grill, Al Tazaj Meat Shop, Al Waha...               88
4   [Al Othman Sweets & Bakery, Olaya Baqala, Al N...               88
5   [Al Subaie Trading Restaurant, Al Shammari Cor...               88
6   [Al Nada Fresh Chilled Foods, Al Noor Mini Mar...               88
7   [Al Rajhi Trading Hospitality Supplies, Al Taz...               88
8   [Al Khaleej Al Sulaymaniyah Baqala, Al Manar A...               88
9   [Al Nakheel Grill, Al Tazaj Meat Shop, Al Dana...               88
10  [Al Manar Al Malaz Hotel Kitchen, Olaya Baqala...               88
11  [Al Subaie Trading Restaurant, Al Harbi Market...               88
12  [Al Ghamdi Trading Hospitality Supplies, Olaya...               88
13  [Al Nada Fresh Mini Market, Al Rawabi Baqala, ...               88
14  [Al Manar Al Sulaymaniyah Cold Store, Al Tazaj...               88
15  [Al Nakheel Grill, Al Tazaj Meat Shop, Al Waha...               88
16  [Al Othman Sweets & Bakery, Al Ghamdi Trading ...               88
17  [Al Subaie Trading Restaurant, Al Noor Mini Ma...               88
18  [Al Ghamdi Trading Hospitality Supplies, Al Wa...               88
19  [Al Dana Fresh Coffee House, Al Tazaj Fresh Me...               88
20  [Al Subaie Trading Restaurant, Al Manar Al Sul...               88
21  [Al Nakheel Grill, Al Dana Oven, Al Waha Fresh...               88
22  [Al Manar Al Malaz Hotel Kitchen, Al Mutairi T...               88
23  [Al Jazeera Fresh Cafe, Al Rashid Trading Hype...               66
24  [Al Waha Fresh Frozen Foods, Al Shammari Corne...               88
25  [Al Tazaj Fresh Restaurant, Al Baraka Fresh Ba...               44

    total_travel_min
0                340
1                385
2                347
3                365
4                381
5                367
6                328
7                392
8                341
9                324
10               323
11               342
12               355
13               340
14               352
15               374
16               332
17               363
18               310
19               389
20               365
21               380
22               386
23               371
24               383
25               254  , assigned_customers=     customer_id                                shop_name    gps_lat  \
0   CUS_RUH_0004                       Al Waha Fresh Meat  24.769710
3   CUS_RUH_0021             Al Subaie Trading Restaurant  24.662204
6   CUS_RUH_0037                             Al Dana Oven  24.714400
9   CUS_RUH_0049                Al Shammari Corner Market  24.714427
12  CUS_RUH_0067                      Al Noor Mini Market  24.701856
15  CUS_RUH_0090                         Al Nakheel Grill  24.685095
18  CUS_RUH_0093                    Al Jazeera Fresh Cafe  24.765842
20  CUS_RUH_0012          Al Manar Al Malaz Hotel Kitchen  24.655689
22  CUS_RUH_0028    Al Rajhi Trading Hospitality Supplies  24.671622
24  CUS_RUH_0043   Al Ghamdi Trading Hospitality Supplies  24.656445
26  CUS_RUH_0075              Al Nada Fresh Chilled Foods  24.675328
28  CUS_RUH_0029                       Al Tazaj Meat Shop  24.692095
30  CUS_RUH_0054      Al Manar Al Sulaymaniyah Cold Store  24.708594
32  CUS_RUH_0063               Al Waha Fresh Frozen Foods  24.706529
35  CUS_RUH_0100                          Al Harbi Market  24.704661
37  CUS_RUH_0023                Al Tazaj Fresh Restaurant  24.826289
39  CUS_RUH_0026          Al Madina Fresh Banquet Kitchen  24.836356
41  CUS_RUH_0045            Al Dossari Trading Hyper Mini  24.815137
43  CUS_RUH_0056             Al Rashid Trading Hyper Mini  24.831748
45  CUS_RUH_0078                     Al Qassim Cold Store  24.829538
47  CUS_RUH_0084          Al Baraka Fresh Banquet Kitchen  24.831661
50  CUS_RUH_0008                              Hittin Cafe  24.761057
51  CUS_RUH_0022                      Al Tazaj Fresh Meat  24.750129
54  CUS_RUH_0069              Al Riyadh Hittin Hyper Mini  24.748086
56  CUS_RUH_0076            Al Harbi Hospitality Supplies  24.775863
58  CUS_RUH_0097       Al Safa Fresh Hospitality Supplies  24.766764
60  CUS_RUH_0007                              Olaya Grill  24.701275
62  CUS_RUH_0030                           Al Tazaj Grill  24.715202
65  CUS_RUH_0047  Al Mutairi Trading Hospitality Supplies  24.720661
66  CUS_RUH_0065                    Al Dana Hotel Kitchen  24.713911
69  CUS_RUH_0087              Al Nakheel Fresh Hyper Mini  24.716498
71  CUS_RUH_0009                Al Nada Fresh Mini Market  24.661470
74  CUS_RUH_0018                         Al Rawabi Baqala  24.663263
76  CUS_RUH_0050               Al Dana Fresh Coffee House  24.652730
79  CUS_RUH_0094                Al Othman Sweets & Bakery  24.663261
83  CUS_RUH_0070        Al Khaleej Al Sulaymaniyah Baqala  24.706986
84  CUS_RUH_0003              Al Qassim Al Yasmin Grocery  24.844884
87  CUS_RUH_0044           Al Nada Fresh Catering Kitchen  24.821430
90  CUS_RUH_0073                    Al Rawabi Mini Market  24.818397
93  CUS_RUH_0089                 Al Nakheel Corner Market  24.824256
95  CUS_RUH_0027                 Al Nakheel Fresh Kitchen  24.764633
97  CUS_RUH_0083                         Al Baraka Bakery  24.758252
99  CUS_RUH_0099                             Olaya Baqala  24.715520

      gps_lng         locality territory_id  customer_rating  review_rating  \
0   46.596453           Hittin      TER_RUH                2            3.7
3   46.732799         Al Malaz      TER_RUH                2            3.4
6   46.673677            Olaya      TER_RUH                4            2.9
9   46.684292            Olaya      TER_RUH                3            3.3
12  46.697032  Al Sulaymaniyah      TER_RUH                5            4.2
15  46.705745  Al Sulaymaniyah      TER_RUH                5            4.1
18  46.594756           Hittin      TER_RUH                2            4.0
20  46.745293         Al Malaz      TER_RUH                4            3.3
22  46.753414         Al Malaz      TER_RUH                1            3.7
24  46.728082         Al Malaz      TER_RUH                4            4.1
26  46.715115         Al Malaz      TER_RUH                2            3.7
28  46.704980  Al Sulaymaniyah      TER_RUH                2            4.5
30  46.699118  Al Sulaymaniyah      TER_RUH                1            4.4
32  46.710297  Al Sulaymaniyah      TER_RUH                4            3.5
35  46.721276  Al Sulaymaniyah      TER_RUH                4            4.3
37  46.642652        Al Yasmin      TER_RUH                2            4.2
39  46.631280        Al Yasmin      TER_RUH                1            3.8
41  46.636076        Al Yasmin      TER_RUH                4            3.5
43  46.640400        Al Yasmin      TER_RUH                2            5.0
45  46.630765        Al Yasmin      TER_RUH                4            3.6
47  46.614555        Al Yasmin      TER_RUH                5            4.5
50  46.603037           Hittin      TER_RUH                3            3.2
51  46.612277           Hittin      TER_RUH                3            4.7
54  46.590569           Hittin      TER_RUH                1            4.3
56  46.602997           Hittin      TER_RUH                3            3.4
58  46.594477           Hittin      TER_RUH                4            3.9
60  46.657092            Olaya      TER_RUH                5            4.8
62  46.668033            Olaya      TER_RUH                3            4.3
65  46.659342            Olaya      TER_RUH                2            4.1
66  46.659157            Olaya      TER_RUH                4            4.1
69  46.684203            Olaya      TER_RUH                5            3.5
71  46.736475         Al Malaz      TER_RUH                3            3.4

In [27]:
import pandas as pd

# Define the output file name
excel_file_path = "monthly_plan.xlsx"

with pd.ExcelWriter(excel_file_path, engine="openpyxl") as writer:
    # 1. Save the main aggregated dataframes to their own sheets
    result.detailed_schedule.to_excel(
        writer, sheet_name="Detailed Schedule", index=False
    )
    result.daily_schedule.to_excel(writer, sheet_name="Daily Schedule", index=False)

    # 2. Loop through the salesperson dictionary and write each to a sheet
    for name, sp_result in result.salesperson_results.items():
        # Excel sheet names cannot exceed 31 characters
        safe_sheet_name = f"SP_{name}"

        # Check if the salesperson result object itself has dataframes to unpack
        # If it is a dictionary, use: sp_result_dict = sp_result
        # If it is another dataclass, convert it to a dict to read its attributes
        if hasattr(sp_result, "__dataclass_fields__"):
            from dataclasses import asdict

            sp_data = asdict(sp_result)
        elif isinstance(sp_result, dict):
            sp_data = sp_result
        else:
            # Fallback: tries to extract internal attributes if it's a custom class
            sp_data = vars(sp_result)

        # Look for any pandas DataFrames inside the salesperson's data to save
        for key, value in sp_data.items():
            if isinstance(value, pd.DataFrame):
                # Creates a unique sheet name like "SP_John_detailed"
                sub_sheet_name = f"SP_{name}_{key}"
                value.to_excel(writer, sheet_name=sub_sheet_name, index=False)

print(f"Successfully saved results to {excel_file_path}")

d:\Data Science\Basamh\JP\journey-planner\.venv\Lib\site-packages\openpyxl\workbook\child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

Successfully saved results to monthly_plan.xlsx

In [ ]:
from saudi_multi_salesperson_scheduler import MultiSalespersonScheduler, build_route_map_for_salesperson
scheduler = MultiSalespersonScheduler(
    extra_champion_bonus=30,
    solver_time_seconds=60,
)

result = scheduler.create_schedules(
    customer_df      = customer_df,
    rfm_scores_df    = rfm_scores_df,
    salesperson_df   = salesperson_df,
    holiday_df       = holiday_df,
    territory_df     = territory_df,
    config_df        = config_df,
    van_df           = van_df,
    month_start_date = "2026-06-01",
)

print(result.detailed_schedule.head(20))
print(result.daily_schedule.head(20))

for sales_id, sp in result.salesperson_results.items():
    print(f"{sales_id} → {len(sp.assigned_customers)} customers, {len(sp.detailed_schedule)} visits")
    
m = build_route_map_for_salesperson(
    daily_schedule    = result.daily_schedule,
    detailed_schedule = result.detailed_schedule,
    sales_id          = "SAL_DMM_001",
    schedule_date     = "2026-06-14",
)
m

Status: OPTIMAL
Objective value: 64656255.0
Best bound: 64656255.0
Status: OPTIMAL
Objective value: 43551210.0
Best bound: 43551210.0
Status: OPTIMAL
Objective value: 64630255.0
Best bound: 64630255.0
Status: OPTIMAL
Objective value: 48447255.0
Best bound: 48447255.0
Status: OPTIMAL
Objective value: 45370210.0
Best bound: 45370210.0
Status: OPTIMAL
Objective value: 80770315.0
Best bound: 80770315.0
Status: OPTIMAL
Objective value: 80775405.0
Best bound: 80775405.0
Status: OPTIMAL
Objective value: 75808240.0
Best bound: 75808240.0
   schedule_date     sales_id territory_id   customer_id  \
0     2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0001
1     2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0002
2     2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0019
3     2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0080
4     2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0098
5     2026-06-14  SAL_DMM_001      TER_DMM  CUS_DMM_0012
6     2026-06-14  SAL_DMM_001      TER_DMM  CUS_DMM_0027
7     2026-06-14  SAL_DMM_001      TER_DMM  CUS_DMM_0056
8     2026-06-14  SAL_DMM_001      TER_DMM  CUS_DMM_0067
9     2026-06-14  SAL_DMM_001      TER_DMM  CUS_DMM_0078
10    2026-06-15  SAL_DMM_001      TER_DMM  CUS_DMM_0009
11    2026-06-15  SAL_DMM_001      TER_DMM  CUS_DMM_0034
12    2026-06-15  SAL_DMM_001      TER_DMM  CUS_DMM_0041
13    2026-06-15  SAL_DMM_001      TER_DMM  CUS_DMM_0053
14    2026-06-15  SAL_DMM_001      TER_DMM  CUS_DMM_0099
15    2026-06-16  SAL_DMM_001      TER_DMM  CUS_DMM_0001
16    2026-06-16  SAL_DMM_001      TER_DMM  CUS_DMM_0047
17    2026-06-16  SAL_DMM_001      TER_DMM  CUS_DMM_0051
18    2026-06-16  SAL_DMM_001      TER_DMM  CUS_DMM_0054
19    2026-06-16  SAL_DMM_001      TER_DMM  CUS_DMM_0098

                             shop_name       locality    gps_lat    gps_lng  \
0         Al Shehri Trading Fresh Meat   Al Mazruiyah  26.456625  50.084601
1             Al Safa Catering Kitchen       Al Shati  26.485366  50.117601
2        Al Tazaj Hospitality Supplies     Al Badiyah  26.431079  50.059445
3             Al Dana Fresh Food Store   Al Mazruiyah  26.436857  50.108580
4               Al Rawabi Fresh Baqala       Al Nuzha  26.439413  50.056715
5              Al Riyadh Corner Market     Al Badiyah  26.397293  50.045975
6               Al Qahtani Mini Market   Al Mazruiyah  26.458637  50.112193
7              Al Anazi Trading Market       Al Nuzha  26.425781  50.042860
8     Al Rajhi Trading Sweets & Bakery  Al Faisaliyah  26.428519  50.078974
9            Al Riyadh Banquet Kitchen   Al Mazruiyah  26.437755  50.083570
10            Al Dossari Corner Market   Al Mazruiyah  26.466041  50.089770
11                Al Safa Fresh Market       Al Nuzha  26.431618  50.036726
12                   Al Riyadh Grocery   Al Mazruiyah  26.451566  50.074690
13            Al Rashid Trading Baqala   Al Mazruiyah  26.453655  50.098525
14  Al Tazaj Al Mazruiyah Frozen Foods   Al Mazruiyah  26.463665  50.104359
15        Al Shehri Trading Fresh Meat   Al Mazruiyah  26.456625  50.084601
16            Al Anazi Trading Grocery       Al Shati  26.488855  50.125161
17            Al Subaie Trading Bakery     Al Badiyah  26.391703  50.041706
18     Al Rawabi Fresh Sweets & Bakery       Al Shati  26.477986  50.105158
19              Al Rawabi Fresh Baqala       Al Nuzha  26.439413  50.056715

               segment lifecycle_state  cold_truck_required  \
0                Loyal          Active                 True
1             Champion          Active                 True
2       Need Attention          Active                 True
3             Champion          Active                False
4                Loyal          Active                False
5             Champion          Active                False
6       Need Attention             New                False
7                Loyal         Dormant                False
8             Champion             New                False
9                Loyal          Active                 True
10  Potential Loyalist          Active                False
11      Need Attention         At Risk                False
12            Champion             New                False
13            Champion          Active                False
14               Loyal         Dormant                 True
15               Loyal          Active                 True
16            Champion          Active                False
17      Need Attention          Active                 True
18  Potential Loyalist          Active                 True
19               Loyal          Active                False

    estimated_visit_minutes  estimated_travel_minutes
0                        22                        74
1                        22                        82
2                        22                        69
3                        22                        63
4                        22                        72
5                        22                        61
6                        22                        71
7                        22                        71
8                        22                        64
9                        22                        67
10                       22                        77
11                       22                        74
12                       22                        74
13                       22                        71
14                       22                        74
15                       22                        74
16                       22                        83
17                       22                        61
18                       22                        80
19                       22                        72
   schedule_date     sales_id territory_id  \
0     2026-06-09  SAL_DMM_001      TER_DMM
1     2026-06-14  SAL_DMM_001      TER_DMM
2     2026-06-15  SAL_DMM_001      TER_DMM
3     2026-06-16  SAL_DMM_001      TER_DMM
4     2026-06-17  SAL_DMM_001      TER_DMM
5     2026-06-18  SAL_DMM_001      TER_DMM
6     2026-06-20  SAL_DMM_001      TER_DMM
7     2026-06-21  SAL_DMM_001      TER_DMM
8     2026-06-22  SAL_DMM_001      TER_DMM
9     2026-06-23  SAL_DMM_001      TER_DMM
10    2026-06-24  SAL_DMM_001      TER_DMM
11    2026-06-25  SAL_DMM_001      TER_DMM
12    2026-06-27  SAL_DMM_001      TER_DMM
13    2026-06-28  SAL_DMM_001      TER_DMM
14    2026-06-29  SAL_DMM_001      TER_DMM
15    2026-06-30  SAL_DMM_001      TER_DMM
16    2026-06-09  SAL_DMM_002      TER_DMM
17    2026-06-14  SAL_DMM_002      TER_DMM
18    2026-06-15  SAL_DMM_002      TER_DMM
19    2026-06-16  SAL_DMM_002      TER_DMM

                                        customer_list  customer_count  \
0   [CUS_DMM_0080, CUS_DMM_0001, CUS_DMM_0098, CUS...               5
1   [CUS_DMM_0012, CUS_DMM_0056, CUS_DMM_0067, CUS...               5
2   [CUS_DMM_0053, CUS_DMM_0099, CUS_DMM_0009, CUS...               5
3   [CUS_DMM_0051, CUS_DMM_0098, CUS_DMM_0001, CUS...               5
4   [CUS_DMM_0080, CUS_DMM_0096, CUS_DMM_0066, CUS...               5
5   [CUS_DMM_0080, CUS_DMM_0053, CUS_DMM_0008, CUS...               5
6   [CUS_DMM_0022, CUS_DMM_0041, CUS_DMM_0053, CUS...               5
7   [CUS_DMM_0012, CUS_DMM_0056, CUS_DMM_0067, CUS...               5
8   [CUS_DMM_0064, CUS_DMM_0026, CUS_DMM_0069, CUS...               5
9   [CUS_DMM_0064, CUS_DMM_0098, CUS_DMM_0001, CUS...               5
10  [CUS_DMM_0082, CUS_DMM_0096, CUS_DMM_0080, CUS...               5
11  [CUS_DMM_0082, CUS_DMM_0067, CUS_DMM_0008, CUS...               5
12  [CUS_DMM_0044, CUS_DMM_0053, CUS_DMM_0095, CUS...               5
13  [CUS_DMM_0044, CUS_DMM_0067, CUS_DMM_0078, CUS...               5
14  [CUS_DMM_0069, CUS_DMM_0041, CUS_DMM_0009, CUS...               5
15  [CUS_DMM_0051, CUS_DMM_0022, CUS_DMM_0019, CUS...               5
16  [CUS_DMM_0070, CUS_DMM_0020, CUS_DMM_0068, CUS...               5
17  [CUS_DMM_0050, CUS_DMM_0057, CUS_DMM_0011, CUS...               5
18  [CUS_DMM_0084, CUS_DMM_0014, CUS_DMM_0060, CUS...               5
19  [CUS_DMM_0020, CUS_DMM_0050, CUS_DMM_0068, CUS...               5

                                          route_order  total_visit_min  \
0   [Al Dana Fresh Food Store, Al Shehri Trading F...              110
1   [Al Riyadh Corner Market, Al Anazi Trading Mar...              110
2   [Al Rashid Trading Baqala, Al Tazaj Al Mazruiy...              110
3   [Al Subaie Trading Bakery, Al Rawabi Fresh Baq...              110
4   [Al Dana Fresh Food Store, Al Manar Butchery, ...              110
5   [Al Dana Fresh Food Store, Al Rashid Trading B...              110
6   [Al Saleh Trading Coffee House, Al Riyadh Groc...              110
7   [Al Riyadh Corner Market, Al Anazi Trading Mar...              110
8   [Al Tazaj Market, Al Mutairi Corner Market, Al...              110
9   [Al Tazaj Market, Al Rawabi Fresh Baqala, Al S...              110
10  [Al Badiyah Grocery, Al Manar Butchery, Al Dan...              110
11  [Al Badiyah Grocery, Al Rajhi Trading Sweets &...              110
12  [Al Madina Fresh Corner Market, Al Rashid Trad...              110
13  [Al Madina Fresh Corner Market, Al Rajhi Tradi...              110
14  [Al Mutairi Trading Supermarket, Al Riyadh Gro...              110
15  [Al Subaie Trading Bakery, Al Saleh Trading Co...              110
16  [Al Nada Fresh Hotel Kitchen, Al Tazaj Caterin...              110
17  [Al Subaie Hotel Kitchen, Al Riyadh Fresh Mark...              110
18  [Al Manar Grocery, Al Faisaliyah Meat Shop, Al...              110
19  [Al Tazaj Catering Kitchen, Al Subaie Hotel Ki...              110

    total_travel_min
0                360
1                334
2                370
3                370
4                370
5                369
6                361
7                334
8                323
9                354
10               354
11               359
12               345
13               324
14               362
15               347
16               326
17               336
18               316
19               339
SAL_RUH_001 → 43 customers, 64 visits
SAL_RUH_002 → 14 customers, 43 visits
SAL_RUH_003 → 43 customers, 64 visits
SAL_JED_001 → 20 customers, 48 visits
SAL_JED_003 → 19 customers, 45 visits
SAL_DMM_001 → 32 customers, 80 visits
SAL_DMM_002 → 33 customers, 80 visits
SAL_DMM_003 → 35 customers, 75 visits

In [ ]:
m = build_route_map_for_salesperson(
    daily_schedule    = result.daily_schedule,
    detailed_schedule = result.detailed_schedule,
    sales_id          = "SAL_JED_001",
    schedule_date     = "2026-06-30",
)
m

In [ ]:
m = build_route_map_for_salesperson(
    daily_schedule    = result.daily_schedule,
    detailed_schedule = result.detailed_schedule,
    sales_id          = "SAL_RUH_003",
    schedule_date     = "2026-06-09",
)
m

In [ ]:
result

MultiScheduleResult(detailed_schedule=    schedule_date     sales_id territory_id   customer_id  \
0      2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0001
1      2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0019
2      2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0064
3      2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0080
4      2026-06-09  SAL_DMM_001      TER_DMM  CUS_DMM_0098
..            ...          ...          ...           ...
494    2026-06-29  SAL_RUH_003      TER_RUH  CUS_RUH_0072
495    2026-06-30  SAL_RUH_003      TER_RUH  CUS_RUH_0002
496    2026-06-30  SAL_RUH_003      TER_RUH  CUS_RUH_0005
497    2026-06-30  SAL_RUH_003      TER_RUH  CUS_RUH_0017
498    2026-06-30  SAL_RUH_003      TER_RUH  CUS_RUH_0085

                         shop_name         locality    gps_lat    gps_lng  \
0     Al Shehri Trading Fresh Meat     Al Mazruiyah  26.456625  50.084601
1    Al Tazaj Hospitality Supplies       Al Badiyah  26.431079  50.059445
2                  Al Tazaj Market       Al Badiyah  26.383395  50.064101
3         Al Dana Fresh Food Store     Al Mazruiyah  26.436857  50.108580
4           Al Rawabi Fresh Baqala         Al Nuzha  26.439413  50.056715
..                             ...              ...        ...        ...
494              Al Mutairi Baqala        Al Yasmin  24.834435  46.626288
495      Al Othman Banquet Kitchen           Hittin  24.780751  46.599296
496        Al Manar Fresh Butchery        Al Yasmin  24.829825  46.606460
497             Al Rawabi Roastery         Al Malaz  24.671470  46.713252
498        Al Anazi Trading Bakery  Al Sulaymaniyah  24.725098  46.723998

                segment lifecycle_state  cold_truck_required  \
0                 Loyal          Active                 True
1        Need Attention          Active                 True
2    Potential Loyalist             New                 True
3              Champion          Active                False
4                 Loyal          Active                False
..                  ...             ...                  ...
494             At Risk          Active                False
495               Loyal          Active                 True
496            Champion          Active                 True
497            Champion          Active                 True
498            Champion          Active                False

     estimated_visit_minutes  estimated_travel_minutes
0                         22                        74
1                         22                        69
2                         22                        52
3                         22                        63
4                         22                        72
..                       ...                       ...
494                       22                       130
495                       22                       119
496                       22                       133
497                       22                        56
498                       22                        71

[499 rows x 13 columns], daily_schedule=    schedule_date     sales_id territory_id  \
0      2026-06-09  SAL_DMM_001      TER_DMM
1      2026-06-14  SAL_DMM_001      TER_DMM
2      2026-06-15  SAL_DMM_001      TER_DMM
3      2026-06-16  SAL_DMM_001      TER_DMM
4      2026-06-17  SAL_DMM_001      TER_DMM
..            ...          ...          ...
121    2026-06-25  SAL_RUH_003      TER_RUH
122    2026-06-27  SAL_RUH_003      TER_RUH
123    2026-06-28  SAL_RUH_003      TER_RUH
124    2026-06-29  SAL_RUH_003      TER_RUH
125    2026-06-30  SAL_RUH_003      TER_RUH

                                         customer_list  customer_count  \
0    [CUS_DMM_0064, CUS_DMM_0019, CUS_DMM_0098, CUS...               5
1    [CUS_DMM_0012, CUS_DMM_0056, CUS_DMM_0067, CUS...               5
2    [CUS_DMM_0053, CUS_DMM_0099, CUS_DMM_0009, CUS...               5
3    [CUS_DMM_0051, CUS_DMM_0019, CUS_DMM_0098, CUS...               5
4    [CUS_DMM_0082, CUS_DMM_0096, CUS_DMM_0066, CUS...               5
..                                                 ...             ...
121  [CUS_RUH_0011, CUS_RUH_0085, CUS_RUH_0042, CUS...               4
122  [CUS_RUH_0066, CUS_RUH_0053, CUS_RUH_0006, CUS...               4
123  [CUS_RUH_0034, CUS_RUH_0035, CUS_RUH_0092, CUS...               4
124  [CUS_RUH_0020, CUS_RUH_0053, CUS_RUH_0040, CUS...               4
125  [CUS_RUH_0017, CUS_RUH_0085, CUS_RUH_0002, CUS...               4

                                           route_order  total_visit_min  \
0    [Al Tazaj Market, Al Tazaj Hospitality Supplie...              110
1    [Al Riyadh Corner Market, Al Anazi Trading Mar...              110
2    [Al Rashid Trading Baqala, Al Tazaj Al Mazruiy...              110
3    [Al Subaie Trading Bakery, Al Tazaj Hospitalit...              110
4    [Al Badiyah Grocery, Al Manar Butchery, Al Jaz...              110
..                                                 ...              ...
121  [Al Noor Fresh Cafe, Al Anazi Trading Bakery, ...               88
122  [Al Khaleej Fresh Cold Store, Al Dana Chilled ...               88
123  [Al Jazeera Baqala, Al Malki Trading Catering ...               88
124  [Al Madina Chilled Foods, Al Dana Chilled Food...               88
125  [Al Rawabi Roastery, Al Anazi Trading Bakery, ...               88

     total_travel_min
0                 330
1                 334
2                 370
3                 356
4                 348
..                ...
121               371
122               387
123               308
124               383
125               379

[126 rows x 8 columns], salesperson_results={'SAL_RUH_001': SalespersonScheduleResult(sales_id='SAL_RUH_001', territory_id='TER_RUH', detailed_schedule=   schedule_date     sales_id territory_id   customer_id  \
0     2026-06-09  SAL_RUH_001      TER_RUH  CUS_RUH_0021
1     2026-06-09  SAL_RUH_001      TER_RUH  CUS_RUH_0056
2     2026-06-09  SAL_RUH_001      TER_RUH  CUS_RUH_0093
3     2026-06-09  SAL_RUH_001      TER_RUH  CUS_RUH_0100
4     2026-06-14  SAL_RUH_001      TER_RUH  CUS_RUH_0004
..           ...          ...          ...           ...
59    2026-06-29  SAL_RUH_001      TER_RUH  CUS_RUH_0090
60    2026-06-30  SAL_RUH_001      TER_RUH  CUS_RUH_0021
61    2026-06-30  SAL_RUH_001      TER_RUH  CUS_RUH_0049
62    2026-06-30  SAL_RUH_001      TER_RUH  CUS_RUH_0067
63    2026-06-30  SAL_RUH_001      TER_RUH  CUS_RUH_0093

                       shop_name         locality    gps_lat    gps_lng  \
0   Al Subaie Trading Restaurant         Al Malaz  24.662204  46.732799
1   Al Rashid Trading Hyper Mini        Al Yasmin  24.831748  46.640400
2          Al Jazeera Fresh Cafe           Hittin  24.765842  46.594756
3                Al Harbi Market  Al Sulaymaniyah  24.704661  46.721276
4             Al Waha Fresh Meat           Hittin  24.769710  46.596453
..                           ...              ...        ...        ...
59              Al Nakheel Grill  Al Sulaymaniyah  24.685095  46.705745
60  Al Subaie Trading Restaurant         Al Malaz  24.662204  46.732799
61     Al Shammari Corner Market            Olaya  24.714427  46.684292
62           Al Noor Mini Market  Al Sulaymaniyah  24.701856  46.697032
63         Al Jazeera Fresh Cafe           Hittin  24.765842  46.594756

           segment lifecycle_state  cold_truck_required  \
0         Champion             New                False
1   Need Attention          Active                 True
2         Champion          Active                False
3      Hibernating         At Risk                 True
4         Champion          Active                 True
..             ...             ...                  ...
59        Champion          Active                False
60        Champion             New                False
61        Champion          Active                False
62        Champion          Active                False
63        Champion          Active                False

    estimated_visit_minutes  estimated_travel_minutes
0                        22                        48
1                        22                       126
2                        22                       116
3                        22                        65
4                        22                       117
..                      ...                       ...
59                       22                        62
60                       22                        48
61                       22                        77
62                       22                        70
63                       22                       116

[64 rows x 13 columns], daily_schedule=   schedule_date     sales_id territory_id  \
0     2026-06-09  SAL_RUH_001      TER_RUH
1     2026-06-14  SAL_RUH_001      TER_RUH
2     2026-06-15  SAL_RUH_001      TER_RUH
3     2026-06-16  SAL_RUH_001      TER_RUH
4     2026-06-17  SAL_RUH_001      TER_RUH
5     2026-06-18  SAL_RUH_001      TER_RUH
6     2026-06-20  SAL_RUH_001      TER_RUH
7     2026-06-21  SAL_RUH_001      TER_RUH
8     2026-06-22  SAL_RUH_001      TER_RUH
9     2026-06-23  SAL_RUH_001      TER_RUH
10    2026-06-24  SAL_RUH_001      TER_RUH
11    2026-06-25  SAL_RUH_001      TER_RUH
12    2026-06-27  SAL_RUH_001      TER_RUH
13    2026-06-28  SAL_RUH_001      TER_RUH
14    2026-06-29  SAL_RUH_001      TER_RUH
15    2026-06-30  SAL_RUH_001      TER_RUH

                                        customer_list  customer_count  \
0   [CUS_RUH_0021, CUS_RUH_0100, CUS_RUH_0093, CUS...               4
1   [CUS_RUH_0090, CUS_RUH_0029, CUS_RUH_0004, CUS...               4
2   [CUS_RUH_0094, CUS_RUH_0007, CUS_RUH_0099, CUS...               4
3   [CUS_RUH_0021, CUS_RUH_0049, CUS_RUH_0093, CUS...               4
4   [CUS_RUH_0075, CUS_RUH_0067, CUS_RUH_0063, CUS...               4
5   [CUS_RUH_0018, CUS_RUH_0087, CUS_RUH_0078, CUS...               4
6   [CUS_RUH_0070, CUS_RUH_0054, CUS_RUH_0076, CUS...               4
7   [CUS_RUH_0090, CUS_RUH_0037, CUS_RUH_0004, CUS...               4
8   [CUS_RUH_0054, CUS_RUH_0049, CUS_RUH_0047, CUS...               4
9   [CUS_RUH_0043, CUS_RUH_0021, CUS_RUH_0069, CUS...               4
10  [CUS_RUH_0067, CUS_RUH_0049, CUS_RUH_0008, CUS...               4
11  [CUS_RUH_0050, CUS_RUH_0022, CUS_RUH_0097, CUS...               4
12  [CUS_RUH_0054, CUS_RUH_0030, CUS_RUH_0065, CUS...               4
13  [CUS_RUH_0090, CUS_RUH_0067, CUS_RUH_0004, CUS...               4
14  [CUS_RUH_0012, CUS_RUH_0090, CUS_RUH_0054, CUS...               4
15  [CUS_RUH_0021, CUS_RUH_0067, CUS_RUH_0049, CUS...               4

                                          route_order  total_visit_min  \
0   [Al Subaie Trading Restaurant, Al Harbi Market...               88
1   [Al Nakheel Grill, Al Tazaj Meat Shop, Al Waha...               88
2   [Al Othman Sweets & Bakery, Olaya Grill, Olaya...               88
3   [Al Subaie Trading Restaurant, Al Shammari Cor...               88
4   [Al Nada Fresh Chilled Foods, Al Noor Mini Mar...               88
5   [Al Rawabi Baqala, Al Nakheel Fresh Hyper Mini...               88
6   [Al Khaleej Al Sulaymaniyah Baqala, Al Manar A...               88
7   [Al Nakheel Grill, Al Dana Oven, Al Waha Fresh...               88
8   [Al Manar Al Sulaymaniyah Cold Store, Al Shamm...               88
9   [Al Ghamdi Trading Hospitality Supplies, Al Su...               88
10  [Al Noor Mini Market, Al Shammari Corner Marke...               88
11  [Al Dana Fresh Coffee House, Al Tazaj Fresh Me...               88
12  [Al Manar Al Sulaymaniyah Cold Store, Al Tazaj...               88
13  [Al Nakheel Grill, Al Noor Mini Market, Al Wah...               88
14  [Al Manar Al Malaz Hotel Kitchen, Al Nakheel G...               88
15  [Al Subaie Trading Restaurant, Al Noor Mini Ma...               88

    total_travel_min
0                355
1                365
2                335
3                370
4                309
5                385
6                371
7                380
8                357
9                325
10               383
11               389
12               364
13               379
14               300
15               311  , assigned_customers=     customer_id                                shop_name    gps_lat  \
0   CUS_RUH_0004                       Al Waha Fresh Meat  24.769710
3   CUS_RUH_0021             Al Subaie Trading Restaurant  24.662204
6   CUS_RUH_0037                             Al Dana Oven  24.714400
9   CUS_RUH_0049                Al Shammari Corner Market  24.714427
12  CUS_RUH_0067                      Al Noor Mini Market  24.701856
15  CUS_RUH_0090                         Al Nakheel Grill  24.685095
18  CUS_RUH_0093                    Al Jazeera Fresh Cafe  24.765842
20  CUS_RUH_0012          Al Manar Al Malaz Hotel Kitchen  24.655689
22  CUS_RUH_0028    Al Rajhi Trading Hospitality Supplies  24.671622
24  CUS_RUH_0043   Al Ghamdi Trading Hospitality Supplies  24.656445
26  CUS_RUH_0075              Al Nada Fresh Chilled Foods  24.675328
28  CUS_RUH_0029                       Al Tazaj Meat Shop  24.692095
30  CUS_RUH_0054      Al Manar Al Sulaymaniyah Cold Store  24.708594
32  CUS_RUH_0063               Al Waha Fresh Frozen Foods  24.706529
35  CUS_RUH_0100                          Al Harbi Market  24.704661
37  CUS_RUH_0023                Al Tazaj Fresh Restaurant  24.826289
39  CUS_RUH_0026          Al Madina Fresh Banquet Kitchen  24.836356
41  CUS_RUH_0045            Al Dossari Trading Hyper Mini  24.815137
43  CUS_RUH_0056             Al Rashid Trading Hyper Mini  24.831748
45  CUS_RUH_0078                     Al Qassim Cold Store  24.829538
47  CUS_RUH_0084          Al Baraka Fresh Banquet Kitchen  24.831661
50  CUS_RUH_0008                              Hittin Cafe  24.761057
51  CUS_RUH_0022                      Al Tazaj Fresh Meat  24.750129
54  CUS_RUH_0069              Al Riyadh Hittin Hyper Mini  24.748086
56  CUS_RUH_0076            Al Harbi Hospitality Supplies  24.775863
58  CUS_RUH_0097       Al Safa Fresh Hospitality Supplies  24.766764
60  CUS_RUH_0007                              Olaya Grill  24.701275
62  CUS_RUH_0030                           Al Tazaj Grill  24.715202
65  CUS_RUH_0047  Al Mutairi Trading Hospitality Supplies  24.720661
66  CUS_RUH_0065                    Al Dana Hotel Kitchen  24.713911
69  CUS_RUH_0087              Al Nakheel Fresh Hyper Mini  24.716498
71  CUS_RUH_0009                Al Nada Fresh Mini Market  24.661470
74  CUS_RUH_0018                         Al Rawabi Baqala  24.663263
76  CUS_RUH_0050               Al Dana Fresh Coffee House  24.652730
79  CUS_RUH_0094                Al Othman Sweets & Bakery  24.663261
83  CUS_RUH_0070        Al Khaleej Al Sulaymaniyah Baqala  24.706986
84  CUS_RUH_0003              Al Qassim Al Yasmin Grocery  24.844884
87  CUS_RUH_0044           Al Nada Fresh Catering Kitchen  24.821430
90  CUS_RUH_0073                    Al Rawabi Mini Market  24.818397
93  CUS_RUH_0089                 Al Nakheel Corner Market  24.824256
95  CUS_RUH_0027                 Al Nakheel Fresh Kitchen  24.764633
97  CUS_RUH_0083                         Al Baraka Bakery  24.758252
99  CUS_RUH_0099                             Olaya Baqala  24.715520

      gps_lng         locality territory_id  customer_rating  review_rating  \
0   46.596453           Hittin      TER_RUH                2            3.7
3   46.732799         Al Malaz      TER_RUH                2            3.4
6   46.673677            Olaya      TER_RUH                4            2.9
9   46.684292            Olaya      TER_RUH                3            3.3
12  46.697032  Al Sulaymaniyah      TER_RUH                5            4.2
15  46.705745  Al Sulaymaniyah      TER_RUH                5            4.1
18  46.594756           Hittin      TER_RUH                2            4.0
20  46.745293         Al Malaz      TER_RUH                4            3.3
22  46.753414         Al Malaz      TER_RUH                1            3.7
24  46.728082         Al Malaz      TER_RUH                4            4.1
26  46.715115         Al Malaz      TER_RUH                2            3.7
28  46.704980  Al Sulaymaniyah      TER_RUH                2            4.5
30  46.699118  Al Sulaymaniyah      TER_RUH                1            4.4
32  46.710297  Al Sulaymaniyah      TER_RUH                4            3.5
35  46.721276  Al Sulaymaniyah      TER_RUH                4            4.3
37  46.642652        Al Yasmin      TER_RUH                2            4.2
39  46.631280        Al Yasmin      TER_RUH                1            3.8
41  46.636076        Al Yasmin      TER_RUH                4            3.5
43  46.640400        Al Yasmin      TER_RUH                2            5.0
45  46.630765        Al Yasmin      TER_RUH                4            3.6
47  46.614555        Al Yasmin      TER_RUH                5            4.5
50  46.603037           Hittin      TER_RUH                3            3.2
51  46.612277           Hittin      TER_RUH                3            4.7
54  46.590569           Hittin      TER_RUH                1            4.3
56  46.602997           Hittin      TER_RUH                3            3.4
58  46.594477           Hittin      TER_RUH                4            3.9
60  46.657092            Olaya      TER_RUH                5            4.8
62  46.668033            Olaya      TER_RUH                3            4.3
65  46.659342            Olaya      TER_RUH                2            4.1
66  46.659157            Olaya      TER_RUH                4            4.1
69  46.684203            Olaya      TER_RUH                5            3.5
71  46.736475         Al Malaz      TER_RUH                3            3.4
74  46.726712         Al Malaz      TER_RUH                5            4.3
76  46.741568         Al Malaz      TER_RUH                5            4.2
79  46.736507         Al Malaz      TER_RUH                4            4.4
83  46.717584  Al Sulaymaniyah      TER_RUH                3            5.0
84  46.639722        Al Yasmin      TER_RUH                5            3.7
87  46.610959        Al Yasmin      TER_RUH                5            4.0
90  46.627262        Al Yasmin      TER_RUH                2            3.7
93  46.614717        Al Yasmin      TER_RUH                3            4.9
95  46.577551           Hittin      TER_RUH                3            3.9
97  46.594098           Hittin      TER_RUH                3            5.0
99  46.666010            Olaya      TER_RUH                4            4.5

       shop_category  cold_truck_required  ... preferred_order_window recency  \
0           Butchery                 True  ...                 Midday      13
3         Restaurant                False  ...              Afternoon       8
6             Bakery                False  ...                 Midday       8
9        Mini Market                False  ...              Afternoon      11
12       Mini Market                False  ...                Morning       5
15        Restaurant                False  ...              Afternoon       3
18              Cafe                False  ...                Morning      17
20     Hotel Kitchen                 True  ...              Afternoon      11
22     Hotel Kitchen                 True  ...                 Midday     224
24     Hotel Kitchen                 True  ...              Afternoon      41
26        Cold Store                 True  ...              Afternoon      90
28          Butchery                 True  ...                Morning      29
30        Cold Store                 True  ...                 Midday      22
32        Cold Store                 True  ...              Afternoon      51
35       Supermarket                 True  ...                Morning      84
37        Restaurant                 True  ...              Afternoon      52
39  Catering Kitchen                 True  ...              Afternoon     100